### ISSUE TITLE
Github Status Logging 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#136]
Add logging to auto Github status to help debugging
 Source - http://chat.stackoverflow.com/transcript/message/35065767#35065767

**Comment by staabm** [comment]
maybe jeeves should even post into the room that github changed status to "down" or "maintenance" or something

**Comment by krakjoe** [comment]
I like ...

A thing to consider would be an on demand status for other services,
@systems ... lxr, r11lxr, wiki, maybe even news servers ... And of course
@peehaa's mother ....

On 12 Jan 2017 10:37 a.m., "Markus Staab" <notifications@github.com> wrote:

maybe jeeves should even post into the room that github changed status to
"down" or "maintenance" or something

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Room-11/Jeeves/issues/136#issuecomment-272130179>, or mute
the thread

**Comment by PeeHaa** [comment]
@staabm 

> maybe jeeves should even post into the room that github changed status to "down" or "maintenance" or something

That's what it should do now already. But @JayPHP's shoddy coding doesn't always work for some reason.

**Comment by JayPHP** [comment]
#107 related - The Github status posts 'failed' most recently because they posted http://chat.stackoverflow.com/transcript/message/35063407#35063407 here first instead of r11. 

Though I am perfect in every way, I didn't make the status checker multi-room compatible. I think using room storage will fix it. TODO.

**Comment by PeeHaa** [comment]
The plugin is now multi room able.
