### ISSUE TITLE
No handler for Cleverbot plugin if their API is down 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#144]
Any calls picked up by the cleverbot plugin are responded to with '<html>' if the cleverbot API is on the blink.
 Source - http://chat.stackoverflow.com/transcript/message/35230386#35230386

**Comment by Nessworthy** [comment]
Think this is more to do with the package from @PeeHaa.
Quick solution would be checking for a bad response in the package, or we could move to cleverbot.io's API.

**Comment by DaveRandom** [comment]
The package should probably throw if it can't talk to the API

**Comment by PeeHaa** [comment]
In the meantime I have actually moved to the API instead of the scraping the page.

I should still handle broken responses though. Luckily the API returns proper status codes when something went wrong:

https://www.cleverbot.com/api/howto/

> 401: unauthorised due to missing or invalid API key or POST request, the Cleverbot API only accepts GET requests
404: API not found
413: request too large if you send a request over 16Kb
502 or 504: unable to get reply from API server, please contact us
503: too many requests from a single IP address or API key

So we will have to throw on that in https://github.com/PeeHaa/async-chatter-bot.

Also wrap the artax call in a catch so we can rethrow using an async-chatter-bot specific exception.

This way we can just catch the async-chatter-bot exception in jeeves.

**Comment by DaveRandom** [comment]
Closed in favour of https://github.com/PeeHaa/async-chatter-bot/issues/1
