### ISSUE TITLE
Laravel auto-answer

### ISSUE THREAD

**Issue by MagicTrucy** [Room-11/Jeeves#151]
When someone (preferably a new user) says "Laravel", Jeeves could auto-answer "We don't help with Laravel." (or quote [https://chat.stackoverflow.com/transcript/message/35152810#35152810]())

**Comment by JayPHP** [comment]
I think this gives the wrong (unwelcoming) message and will be spammy. Shit or not, Laravel is one of the most popular frameworks and questions regarding it should be expected in a PHP Room.

I think the statement "We don't help with Laravel." is also incorrect. Most 'Laravel questions' that are asked in R11 can be generalised to PHP, which is something we can help with.

Finally, if a user is using a system that we do not like - we should probably take the time to explain to them, in a polite manner, why they're decision is wrong, rather than alienating them and making them feel unwelcome.
