### ISSUE TITLE
!!rfc voting totals up to 99% when it doesn't divide cleanly. 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#170]
http://chat.stackoverflow.com/transcript/message/35752206#35752206
 Source - http://chat.stackoverflow.com/transcript/message/35752225#35752225

**Comment by Nessworthy** [comment]
Either Jeeves is given an extra bit of precision or it can bump the highest choice ones up until it totals 100%.

**Comment by pcrov** [comment]
I'd rather remove the percentages - they aren't all that relevant and rounding could give a misleading impression of the state of an rfc (e.g. 66.5% rounded up to 67% would show a 2/3-required vote as passing rather than failing.)

If the passing requirements (50%+1 or 2/3) can be teased out of the rfc an indication of passing/not-passing could be added to the message, otherwise just give the counts and leave the rest to the readers.

**Comment by kelunik** [comment]
Just format it as `xy.z%` and ignore any possibly missing 0.1%.
