### ISSUE TITLE
Change KeyValue store to not throw

### ISSUE THREAD

**Issue by kelunik** [Room-11/Jeeves#192]
It _might_ make sense for `get` to throw on non-existent keys, but it definitely doesn't make sense to throw on `unset` for non-existent keys.

**Comment by ralt** [comment]
Why? `unlink` on a non-existing file throws ENOENT, so this kind of interface makes sense to me.

**Comment by DaveRandom** [comment]
In an async environment, I'm inclined to agree. Since it wouldn't be possible to atomically check if a key exists before `unset()`, it's making it harder to use for a consumer.

The same is probably true of `get()`, if we change that then you'd lose the current ability to store explicit `null` but I don't think that's particularly useful in the general case here anyway.

**Comment by Nessworthy** [comment]
Use case wise, as long as there is a check for a key existing then nothing will be lost by removing the throw. 
If there ever was a use case where you need to know if there was a key before removal then it makes more sense to not rely on an exception, but explicitly checking prior to unset anyway.

**Comment by kelunik** [comment]
> The same is probably true of get(), if we change that then you'd lose the current ability to store explicit null but I don't think that's particularly useful in the general case here anyway.

***Stop using `null` to have a meaning.***
