### ISSUE TITLE
Replace Google Plugin with LMGTFY

### ISSUE THREAD

**Issue by kelunik** [Room-11/Jeeves#62]
The Google results are rather spam than helpful. I think we should replace the results with a link to http://lmgtfy.com/.

**Comment by Nessworthy** [comment]
I remember seeing dissuasion from lmgtfy because it can come across as condescending (even though that's half of the point), though I'm not sure there's a better alternative other than posting a direct link to google instead.

**Comment by DaveRandom** [comment]
I think it could be worthwhile limiting the people who can use it

**Comment by DaveRandom** [comment]
I have unmapped `!!google` for now. `!!?` still works, but most people don't know this.

**Comment by JayPHP** [comment]
lmgtfy is frowned upon in main site, I don't think we should encourage it within chat. Maybe making the !!google response shorter could make it seem less spammy.
I agree with @Nessworthy, it's condescending and rude.

**Comment by kelunik** [comment]
> I agree with @Nessworthy, lmgtfy is condescending and rude.

Well, what's the purpose of this plugin after all?

**Comment by oldskool** [comment]
> Well, what's the purpose of this plugin after all?

I thought it was to help you when you're too lazy to open a new tab to google something yourself. 😉 
But I agree with the critiques, I don't really see how adding this improves the plugin. We might as well make it spam images like this while it's at it:

![Dumbass](http://s2.quickmeme.com/img/a6/a63c59ed368eb956d1de94264481019c3e34f9f547abfe5a2fbc263a9f4303d3.jpg)

**Comment by DaveRandom** [comment]
OK in order to close this issue, how does this work for everyone:

We add a separate lmgtfy plugin. The command `!!google` can then be mapped to either, depending on what the room wants at the time.

**Comment by kelunik** [comment]
Currently I'd vote to remove / disable the plugin completely instead. It's hardly useful.

**Comment by JayPHP** [comment]
I don't think there's a place for lmgtfy on SO, and again it's discouraged by moderators. I think the current google plugin has it's benefits.

**Comment by DaveRandom** [comment]
The point here is not what *we* do in 11, it's about having the option to do whatever you like. Whatever plugin you want can be enabled/disabled and have whatever commands you like mapped to it on a per-room basis.

I would like to close this issue off because it's just sort of sitting here staring at me like the weird guy on the bus who just stands there with his penis out and looks you straight in the eye.

It seems to me that we can can solve the issue at the Jeeves level by creating an lmgtfy plugin, so that the option exists, and we can discuss what wee do in 11... in 11.

My $0.02

**Comment by JayPHP** [comment]
Yeah, I did have R11 in mind which is wrong now that Jeeves is going GLOBAL. 

Is there any great urgency for the plugin? Because if not, I wouldn't mind giving it a shot as it seems easy enough.

Unrelated: but if you could tell me the exact route, bus number and time I'd appreciate it. Just asking for a friend.

**Comment by PeeHaa** [comment]
Wait wat. I can actually juat pick you up at a busstop @jayphp. So I went to phpnw for nothing?

**Comment by JayPHP** [comment]
@PeeHaa I was just playing hard to get

**Comment by DaveRandom** [comment]
@JayPHP happy for you to do it, there's no urgency, just as someone is doing something to move this issue along.

The existing Google plugin is pretty complex because there's so much pre/post processing going on, so if this if you first dive into the plugin API I recommend you start by looking at something simpler like [Questionify](https://github.com/Room-11/Jeeves/blob/master/src/Plugins/Questionify.php), since all the lmgtfy plugin needs to do initially is reformat text into a link. Once you have that working, you can look at other stuff like accepting message refs instead of text.

Also [here is the plugin API reference](https://github.com/Room-11/Jeeves/wiki/The-Plugin-API), because no-one seems to realise we have a wiki because usually no-one bothers to write one.

**Comment by DaveRandom** [comment]
https://github.com/Room-11/Jeeves/pull/100
